name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java and code build
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: |
          java -version
          mvn -version
          mvn clean install
          mvn test
          
       
          
     
        env:
          GITHUB TOKEN: ${{ secrets. GITHUB_TOKEN }} # Needed to get PR information, if an
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:-Dsonar.projectKey=sathya-java


