name: Java CICD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  workflow_dispatch:
    inputs:
    #   branch:
    #     description: 'The branch to build'
    #     required: true
      environment:
        description: 'The environment to deploy to'
        required: false
jobs:
  checkersion:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        version: [10, 12, 14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}